// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4tBxugdqgrTI_rqA1GW7UqnJMVZUdcv8',
    appId: '1:317463472451:web:083637074d5e88b9aa67f6',
    messagingSenderId: '317463472451',
    projectId: 'loan-countdown',
    authDomain: 'loan-countdown.firebaseapp.com',
    storageBucket: 'loan-countdown.firebasestorage.app',
    measurementId: 'G-YN29V4SQXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdqQ3_FCdYO9BfbkbzxLohcuwfbwlBen8',
    appId: '1:317463472451:android:767f45df76d1b966aa67f6',
    messagingSenderId: '317463472451',
    projectId: 'loan-countdown',
    storageBucket: 'loan-countdown.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5bhj-h2rQHy6EM136jZ02sf4SauuosxU',
    appId: '1:317463472451:ios:2555d7ca355bc91baa67f6',
    messagingSenderId: '317463472451',
    projectId: 'loan-countdown',
    storageBucket: 'loan-countdown.firebasestorage.app',
    iosBundleId: 'juny.loanCountdown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5bhj-h2rQHy6EM136jZ02sf4SauuosxU',
    appId: '1:317463472451:ios:4053589745b4910eaa67f6',
    messagingSenderId: '317463472451',
    projectId: 'loan-countdown',
    storageBucket: 'loan-countdown.firebasestorage.app',
    iosBundleId: 'com.example.loancountdown.loanCountdown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4tBxugdqgrTI_rqA1GW7UqnJMVZUdcv8',
    appId: '1:317463472451:web:a55e7ee5884a1e6caa67f6',
    messagingSenderId: '317463472451',
    projectId: 'loan-countdown',
    authDomain: 'loan-countdown.firebaseapp.com',
    storageBucket: 'loan-countdown.firebasestorage.app',
    measurementId: 'G-LF2JZF0PQ0',
  );
}
